name = "SpBNPTrack"
uuid = "34fb1bd2-35c9-4575-83d4-13ca8a095b37"
authors = ["lanceXwq <lance.xwq@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
