name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        julia-version: ["1.11", "nightly"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@v2.6.1
        with:
          version: ${{ matrix.julia-version }}
          # Include prereleases when matching the Julia version to available versions.
          # include-all-prereleases: "false"
          arch: "default"
          show-versioninfo: "false"
          # The path to the project directory or file to use when resolving some versions (e.g. min)
          # project: # optional, default is 

      # - name: Install dependencies
      #   run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      # - name: Run tests
      #   run: julia --project=. -e 'using Pkg; Pkg.test()'