name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ["1.11", "pre"]
        julia-arch: [x64, arm64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x64
          - os: ubuntu-latest
            julia-arch: arm64
          - os: windows-latest
            julia-arch: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2.6.1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2.1.0
      - uses: julia-actions/julia-buildpkg@v1.0.1
      - uses: julia-actions/julia-runtest@v1.11.2
        # with:
        #   annotate: true
